HeatRate = 1.0/40 # rate in unit per min
SampleRateInSec = 60
ControlRelayNum = 0
ThresholdFactor = 0.2
#BolilerControlerDir = '//home//pi//Boiler'
#BolilerControlerHostName = 'marellypi'
#CalendarLocalPath = 'E:\BoilerProject\PiCode\BoilerControler\Cal.json'
#ManualLocalPath = 'E:\BoilerProject\PiCode\BoilerControler\manual.json'
#StatusFileName = 'E:\BoilerProject\PiCode\BoilerControler\temp.txt.current'
CalendarLocalPath = 'Cal.json'
ManualLocalPath = 'manual.json'
StatusFileName = 'temp.txt.current'
LogFileName = "temp.txt"
RestAPIAllowedIP = ""
TimerCalendarLocalPath = 'TimeCal.json'
TimerManualLocalPath = 'Timemanual.json'
TimerSampleRateInSec = 30