CLIENT_SECRET_FILE = 'client_secret.json'
AdminEmailList = 'eran.marelly@verint.com;emarelly@gmail.com;offekmarelly@gmail.com'
UserEmailList = 'oskeren@gmail.com;shahafm1@gmail.com;offekmarelly@gmail.com;eran.marelly@verint.com;emarelly@gmail.com'
BolilerControlerDir = '//home//pi//Boiler'
BolilerControlerHostName = 'marellypi'
#BoilerXMLFileName = 'XMLFile1.xml'
CalendarLocalPath = 'Cal.json'
TimerCalendarLocalPath = 'TimeCal.json'
ManCalendarLocalPath ='manual.json'
TimerManCalendarLocalPath ='Timemanual.json'
RefreshTime = 30
USER = 'pi'
PASS = 'kerenm1'
StatusFileName = 'temp.txt.current'
MaxFailures = 5
# rest API url
baseRestURL = 'http://MARELLYPI3:8000/'
GetLogURL = baseRestURL + 'log/' 
GetStatusURL = baseRestURL + 'status/'
GetRelayStatusURL = baseRestURL + 'relay/?relay='
PostUpdateCalURL = baseRestURL + 'updatecalander/'
PostUpdateManualCalOnURL = baseRestURL + 'manualon/'
PostUpdateManualCalOffURL = baseRestURL + 'manualoff/'
PostUpdateManualRelayOffURL = baseRestURL + 'relayoff/'
PostUpdateManualRelayOnURL = baseRestURL + 'relayon/'
PostUpdateRelayURL = baseRestURL + 'updaterelaycalander/'